# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'team.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 130, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 180, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 180, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 180, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(620, 180, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(90, 240, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(310, 230, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 230, 93, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(122, 290, 111, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(352, 290, 111, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(592, 290, 121, 28))
        self.pushButton_11.setObjectName("pushButton_11")
        self.players_label = QtWidgets.QLabel(self.centralwidget)
        self.players_label.setGeometry(QtCore.QRect(330, 400, 55, 16))
        self.players_label.setObjectName("players_label")
        self.position_combo = QtWidgets.QComboBox(self.centralwidget)
        self.position_combo.setGeometry(QtCore.QRect(230, 10, 311, 22))
        self.position_combo.setObjectName("position_combo")
        self.position_combo.addItem("")
        self.position_combo.addItem("")
        self.position_combo.addItem("")
        self.position_combo.addItem("")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(500, 60, 120, 80))
        self.widget.setObjectName("widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "მეკარე"))
        self.pushButton_2.setText(_translate("MainWindow", "მცველი"))
        self.pushButton_3.setText(_translate("MainWindow", "მცველი"))
        self.pushButton_4.setText(_translate("MainWindow", "მცველი"))
        self.pushButton_5.setText(_translate("MainWindow", "მცველი"))
        self.pushButton_6.setText(_translate("MainWindow", "ნახ.მცველი"))
        self.pushButton_7.setText(_translate("MainWindow", "ნახ.მცველი"))
        self.pushButton_8.setText(_translate("MainWindow", "ნახ.მცველი"))
        self.pushButton_9.setText(_translate("MainWindow", "თავდამსხმელი"))
        self.pushButton_10.setText(_translate("MainWindow", "თავდამსხმელი"))
        self.pushButton_11.setText(_translate("MainWindow", "თავდამსხმელი"))
        self.players_label.setText(_translate("MainWindow", "TextLabel"))
        self.position_combo.setItemText(0, _translate("MainWindow", "მეკარე"))
        self.position_combo.setItemText(1, _translate("MainWindow", "მცველი"))
        self.position_combo.setItemText(2, _translate("MainWindow", "ნახ.მცველი"))
        self.position_combo.setItemText(3, _translate("MainWindow", "თავდამსხმელი"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
